### ISSUE TITLE
Not able to login thru termux

### ISSUE THREAD

**Issue by arman62** [bhikandeshmukh/instarat#6]
Sir i am not able to login even after entering right credentials

**Comment by bhikandeshmukh** [comment]
Screenshot

**Comment by sLyth7-Inc** [comment]
![Screenshot_2021-07-05-23-45-38-819_com.termux.jpg](https://user-images.githubusercontent.com/84484966/124501087-230c6500-ddeb-11eb-9986-25d1a2654197.jpg)

**Comment by sLyth7-Inc** [comment]
What is this?

**Comment by sLyth7-Inc** [comment]
Challenge required

**Comment by bhikandeshmukh** [comment]
Instagram issue try to fix error free your id than try
