### ISSUE TITLE
increase your followers

### ISSUE THREAD

**Issue by kocebs** [bhikandeshmukh/instarat#8]
Hello, i have problem with option 2 Increase Followers :(

[+] This technique consists of following/unfolling celebgrams
[+] It can increase your followers up to about +30 in 1 hour
[+] Press Ctrl + C to stop
[+] Trying to follow celebgram 259925762 ...
 [!] Error

**Comment by Elunico01** [comment]
I have the same error

**Comment by bhikandeshmukh** [comment]
Don't use instarat more than 1 hr in 1 day instagram ban you
